title: Project
num: "{{ page.sort }}"

status:
  draft:
    label: Draft
    text: Project is not visible
  listed:
    label: Published
    text: Project is visible

columns:
  # Left column - Main content (2/3 width)
  - width: 2/3
    sections:
      content:
        type: fields
        fields:
          blocks:
            type: blocks
            label: Article Content
            fieldsets:
              - b-header
              - b-img
              - b-text
              - b-grid
              - b-fullbleed

  # Right column - Sidebar (1/3 width)
  - width: 1/3
    sticky: true
    sections:
      # Main info
      main:
        type: fields
        label: Main
        fields:
          name:
            type: text
            label: Name
            help: Short name for cards
            required: true
            width: 1/2

          project_title:
            type: text
            label: Title
            help: Full title for detail page
            required: true
            width: 1/2

          description:
            type: writer
            label: Description
            marks:
              - bold
              - italic
              - link

          tags:
            type: tags
            label: Tags
            options:
              - Web Design
              - Branding & Identity
              - Front-end Development
              - Product Design
              - Social Media
              - DevOps

          showcase:
            type: toggle
            label: Featured
            default: true
            width: 1/2

          published:
            type: date
            label: Published
            width: 1/2

      # Images
      images:
        type: fields
        label: Images
        fields:
          thumbnail_base:
            type: files
            label: Thumbnail (Base Layer)
            help: Background image for project card
            max: 1
            width: 1/2
            uploads:
              template: image

          thumbnail_overlay:
            type: files
            label: Thumbnail (Overlay Layer)
            help: Foreground image for project card
            max: 1
            width: 1/2
            uploads:
              template: image

      # SEO
      seo:
        type: fields
        label: SEO
        fields:
          meta_title:
            type: text
            label: Page Title
            help: Leave empty to use project title

          meta_description:
            type: textarea
            label: Meta Description
            maxlength: 160

          meta_image:
            type: files
            label: Opengraph Image
            max: 1
            uploads:
              template: image
