title: Project
num: "{{ page.sort }}"

status:
  draft:
    label: Draft
    text: Project is not visible
  listed:
    label: Published
    text: Project is visible

columns:
  # Left column - Main content (2/3 width)
  - width: 2/3
    sections:
      content:
        type: fields
        fields:
          blocks:
            type: blocks
            label: Article Content
            fieldsets:
              - b-header
              - b-img
              - b-text
              - b-grid
              - b-fullbleed

  # Right column - Sidebar (1/3 width)
  - width: 1/3
    sticky: true
    sections:
      # Main info
      main:
        type: fields
        label: Main
        fields:
          name:
            type: text
            label: Name
            required: true
            width: 1/2

          project_title:
            type: text
            label: Title
            required: true
            width: 1/2

          description:
            type: writer
            label: Description
            marks:
              - bold
              - italic
              - link

          tags:
            type: tags
            label: Tags
            options:
              - Web Design
              - Branding & Identity
              - Front-end Development
              - Product Design
              - Social Media
              - DevOps

          published:
            type: date
            label: Published
            width: 1/2
          thumbnail_base:
            type: files
            label: Thumbnail (Base Layer)
            max: 1
            width: 1/2
            uploads:
              template: image

      # SEO
      seo:
        type: fields
        label: SEO
        fields:
          meta_title:
            type: text
            label: Page Title

          meta_description:
            type: textarea
            label: Meta Description
            maxlength: 160

          meta_image:
            type: files
            label: OpenGraph Image
            max: 1
            uploads:
              template: image
